### ISSUE TITLE
Need help with signing part on executable binary

### ISSUE THREAD

**Issue by tejaskumark** [patcable/onair#2]
@patcable I have been going through your [blog](https://pcable.net/posts/2020-11-14-inetaccesspolicy/#fn:3) for one of my project and I am totally stuck on signing part. I wanted to understand how this signing works and will it work for my projects for which I need Location Services permission. Will you be able to guide me if possible for you?

Thanks.

**Comment by patcable** [comment]
Sorry, i'm not really sure how entitlements (I believe that's what they're called?) work. Maybe something in the Info.plist? Not sure.
