### ISSUE TITLE
Update to info.plist article

### ISSUE THREAD

**Issue by cjappl** [patcable/onair#3]
Hi!

Apologies for the weird form of contact.

I found this article you wrote in 2020, which was massively, massively helpful regarding embedding Info.plist into binaries

https://pcable.net/posts/2020-11-14-inetaccesspolicy/

I went down a rabbit hole because it turns out that `otool` has changed in newer versions of OSX, and now outputs a mangled version if you use

`otool -s __TEXT __info_plist ./path/to/your/binary`

I'm writing this ticket to get in touch with you in case you want to update the article (and help future fools like myself)

The options on OSX Monterey or newer are:

```
otool -P ./path/to/your/binary
```

or, even without xcode can produce similar output with

```
plutil -p ./path/to/your/binary
{
  "BuildMachineOSBuild" => "20F71"
  "CFBundleDevelopmentRegion" => "en"
  "CFBundleInfoDictionaryVersion" => "6.0"
  "CFBundlePackageType" => "APPL"
  "CFBundleShortVersionString" => "10.16.1"
  "CFBundleSupportedPlatforms" => [
    0 => "MacOSX"
  ]
  "NSHumanReadableCopyright" => "Copyright © 2021-2022 SpatialX. All rights reserved."
  "ProcessType" => "Interactive"
}
```

Anyway, thanks for the great article! saved me a lot of pain and suffering

**Comment by patcable** [comment]
Hey, thanks for this! I may update the article at the very least with a link here.
